config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users, only: %i[new create edit update]
  resources :user_sessions, only: %i[new create destroy]

  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout

  scope '/dashboard' do
    resources :packs do
      member do
        post 'set_as_current'
      end
      resources :cards, shallow: true, except: %i[index show]
    end
    post 'card_check_original_text', to: 'cards#check_original_text'
  end

  get 'home/index'
  put 'home/locale'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
# frozen_string_literal: true

# Model responsible for storing oauth authentications
#
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/card.rb
# frozen_string_literal: true

# Model responsible for cards
#
class Card < ApplicationRecord
  belongs_to :pack

  has_attached_file :picture, styles: { original: '360x360>' }
  validates_attachment_content_type :picture, content_type: %r{\Aimage\/.*\z}

  validates :pack_id, :original_text, :translated_text, presence: true
  validates :success_count, :fail_count, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :review_date, presence: true, on: :update
  validate :text_difference

  scope :sort_by_review_date, -> { order(review_date: :desc) }
  scope :sort_by_random, -> { order('RANDOM()') }
  scope :outdated, -> { where('review_date <= ?', Time.now) }

  private

  def text_difference
    return unless original_text.casecmp?(translated_text)
    errors.add(:translated_text, 'Оригинальный и переведенный текст не могут быть одинаковыми')
  end
end

app/models/pack.rb
# frozen_string_literal: true

# Model responsible for packs of cards
# Pack can have many cards
#
class Pack < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# Model responsible for users on site
# User can have many packs
#
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  belongs_to :current_pack, class_name: 'Pack', optional: true
  has_many :packs, dependent: :destroy
  has_many :cards, through: :packs
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true

  scope :with_pending_cards, -> { where(id: Card.joins(:pack).select(:user_id).outdated) }

  def update_current_pack(pack)
    update(current_pack_id: pack.id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

## ApplicationController
#
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def default_url_options
    { locale: I18n.locale }
  end

  private

  def set_locale
    I18n.locale = current_user&.locale || params[:locale] || http_accept_language.compatible_language_from(I18n.available_locales)
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

# Controller responsible for showing and creating cards
#
class CardsController < ApplicationController
  before_action :set_card, only: %i[check_original_text edit update destroy]
  before_action :set_pack, only: %i[new create]
  before_action :require_login

  def check_original_text
    @message = AnswerChecker.new(@card, params[:answer]).result_message
    @pack    = current_user.current_pack
    @card    = FindRandomCard.call(current_user, @pack)

    respond_to do |format|
      format.html { render partial: 'home/card_check' }
      format.js {}
    end
  end

  def new
    @card = Card.new
  end

  def create
    @card = @pack.cards.new(card_params)

    if @card.save
      redirect_to @pack
    else
      render 'cards/new'
    end
  end

  def edit; end

  def update
    if @card.update(card_params)
      redirect_to @card.pack
    else
      render 'cards/edit'
    end
  end

  def destroy
    if @card.destroy
      redirect_to @card.pack
    else
      redirect_to @card.pack, alert: 'Произошла ошибка'
    end
  end

  private

  def set_pack
    @pack = current_user.packs.find(params[:pack_id])
  end

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :picture)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Welcomes user with root action index
#
class HomeController < ApplicationController
  def index
    return unless current_user
    @pack = current_user.current_pack
    @card = FindRandomCard.call(current_user, @pack)
  end

  def locale
    redirect_to root_path(locale: params[:locale])
  end
end

app/controllers/oauths_controller.rb
# frozen_string_literal: true

# Handles oauth authorization
#
class OauthsController < ApplicationController
  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if (@user = login_from(provider))
      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider)
  end
end

app/controllers/packs_controller.rb
# frozen_string_literal: true

# Controller responsible for packs of cards
#
class PacksController < ApplicationController
  before_action :set_pack, only: %i[set_as_current show edit update destroy]
  before_action :require_login

  def set_as_current
    if current_user.update_current_pack(@pack)
      redirect_to packs_path
    else
      redirect_to packs_path, alert: 'Ошибка'
    end
  end

  def index
    @packs = current_user.packs
  end

  def show
    @cards = @pack.cards.sort_by_review_date
  end

  def new
    @pack = Pack.new
  end

  def create
    @pack = current_user.packs.new(pack_params)

    if @pack.save
      redirect_to packs_path
    else
      render 'packs/new'
    end
  end

  def edit; end

  def update
    if @pack.update(pack_params)
      redirect_to packs_path
    else
      render 'packs/edit'
    end
  end

  def destroy
    if @pack.destroy
      redirect_to packs_url
    else
      redirect_to packs_url, alert: 'Произошла ошибка'
    end
  end

  private

  def set_pack
    @pack = current_user.packs.find(params[:id])
  end

  def pack_params
    params.require(:pack).permit(:name)
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

# Responsible for sessions
#
class UserSessionsController < ApplicationController
  def new; end

  def create
    if (@user = login(params[:email], params[:password]))
      redirect_back_or_to root_path, notice: 'Вы успешно вошли!'
    else
      flash.now[:alert] = 'Ошибка'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Вы вышли из системы'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Responsible for creating new user
#
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login @user
      redirect_to root_path, notice: 'Регистрация успешна!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Успешно отредактировано!'
    else
      render 'users/edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :locale)
  end
end

app/views/cards/_form.html.erb
<%= simple_form_for [@pack, @card] do |f| %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <%= f.input :picture, as: :file %>
  <% unless @card.new_record? %>
    <%= f.input :review_date %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/cards/check_original_text.js.erb
$(".js-card-check").html('<%= j(render partial: 'home/card_check') %>');

app/views/cards/edit.html.erb
<h1><%= t('cards.edit') %></h1>
<%= render 'cards/form' %>

app/views/cards/new.html.erb
<h1>Добавить карточку</h1>
<%= render 'cards/form' %>

app/views/home/_card_check.html.erb
<%= @message if @message %>
<br>
<% if @card.present? %>
  <% if @card.picture.present? %>
    <%= image_tag @card.picture.url %>
  <% end %>
  <%= t('cards.translated_text') %>: <%= @card.translated_text %>
  <%= form_tag card_check_original_text_path, class: 'spec-answer-form', remote: true do %>
    <%= hidden_field_tag :id, @card.id %>
    <%= label :answer, t('cards.original_text') %>
    <%= text_field_tag :answer %>
    <%= submit_tag t('home.check') %>
  <% end %>
<% else %>
  <%= t('home.no_cards') %> <%= @pack ? t('home.in_current_deck') : '' %>
<% end %>

app/views/home/index.html.erb
<p style="font-size: 22px;"><%=t('home.welcome')%></p>
<div class="js-card-check">
  <%= render 'card_check' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <flash class=<%="flash-#{key}"%>>
        <%= value %>
      </flash>
    <% end %>
    <section id="container">

      <header class="clearfix">
        <nav class="navbar navbar-default navbar-expand-md">
          <div class="container-fluid">
            <div class="navbar-header">
              <h1><%= link_to t('flashcarder'), home_index_path %></h1>
            </div>
            <ul class="navbar-nav navigation-links">
              <% if current_user %>
                <li class="nav-item"><%= link_to t('edit_profile'), edit_user_path(current_user.id) %></li>
                <li class="nav-item"><%= link_to t('logout'), :logout, method: :post %></li>
                <li class="nav-item"><%= link_to t('packs.all'), packs_path %></li>
                <li class="nav-item"><%= link_to t('packs.add'), new_pack_path %></li>
              <% else %>
                <%= link_to t('registration'), new_user_path %> |
                <%= link_to t('login'), :login %> |
                <%= link_to t('login_github'), auth_at_provider_path(provider: :github) %> |
                <% if I18n.locale == :ru %>
                  <%= link_to 'RU', home_locale_path(locale: 'en'), method: :put %>
                <% else %>
                  <%= link_to 'EN', home_locale_path(locale: 'ru'), method: :put %>
                <% end %>
            <% end %>

            </ul>
          </div>
        </nav>
      </header>

      <section>
        <%= yield %>
      </section>
    </section>
  </body>
</html>

app/views/packs/_form.html.erb
<%= simple_form_for @pack do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/packs/edit.html.erb
<h1><%= t('packs.edit') %></h1>
<%= render 'packs/form' %>

app/views/packs/index.html.erb
<h1><%= t('packs.all') %></h1>
<ul>
  <table>
    <th><%= t('name') %></th>
    <th></th>
    <th></th>
    <th></th>
    <% @packs.each do |pack| %>
      <tr class="rspec-pack">
        <td><%= link_to pack.name, pack %></td>
        <td>
          <% if current_user.current_pack == pack %>
            <%= t('packs.current') %>
          <% else %>
            <%= link_to t('packs.set_current'), set_as_current_pack_path(pack.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to t('edit'), edit_pack_path(pack.id) %></td>
        <td><%= link_to t('delete'), pack, method: :delete, data: { confirm: t('confirm') } %></td>
      </tr>
    <% end %>
  </table>
</ul>

app/views/packs/new.html.erb
<h1><%= t('packs.add') %></h1>
<%= render 'packs/form' %>

app/views/packs/show.html.erb
<h1><%= @pack.name %></h1>
<%= link_to t('cards.add'), new_pack_card_path(@pack), id: 'add-card' %>
<table>
  <th><%= t('cards.original_text') %></th>
  <th><%= t('cards.translated_text') %></th>
  <th><%= t('cards.review_date') %></th>
  <th></th>
  <th></th>
  <% @cards.each do |card| %>
    <tr class="rspec-card">
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date&.strftime('%d/%m/%y') %></td>
      <td><%= link_to t('edit'), edit_card_path(card.id) %></td>
      <td><%= link_to t('delete'), card, method: :delete, data: { confirm: t('confirm') } %></td>
    </tr>
  <% end %>
</table>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag t('login'), id: 'submit-login' %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1><%= t('login') %></h1>

<%= render 'user_sessions/form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :password, required: true %>
  <%= f.input :password_confirmation, required: true %>
  <%= f.input :locale, collection: I18n.available_locales, include_blank: false %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Редактировать</h1>

<%= render 'users/form' %>

app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= render 'users/form' %>